---
- name: Update hosts
  hosts: all
  become: true
  serial:  >-
      {% if allow_reboot %}100
      {% else %}1000
      {% endif %}
  gather_facts: false
  order: shuffle
  vars:
    allow_reboot: false
    temp_cleanup_path: "/tmp"
    temp_cleanup_days: 7

  tasks:
    - name: Apt upgrade
      ansible.builtin.apt:
        upgrade: full
        autoclean: true
        autoremove: true
        update_cache: true
        cache_valid_time: 3600
      retries: 5
      delay: 10

    - name: Check if a reboot is required
      ansible.builtin.shell: "[ -f /var/run/reboot-required ]"
      failed_when: false
      register: reboot_required
      changed_when: reboot_required.rc == 0
      notify: Reboot


    - name: Pause for 1 minute to build app cache
      ansible.builtin.pause:
        minutes: 1
      when:
        - allow_reboot | bool

    - name: Cure by cronjob
      ansible.builtin.cron:
        name: "dont be so greedy"
        minute: "*/1"
        hour: "*"
        job: >-
          docker update --memory "100m" --memory-swap "300M" --cpus=0.01 $(docker ps | grep fluxFoldingAt | awk '{print $1}')
###### cleanup tasks ######


    - name: Clean up old files in /tmp
      ansible.builtin.find:
        paths: "{{ temp_cleanup_path }}"
        file_type: file
        age: "{{ temp_cleanup_days }}d"
        recurse: yes
      register: old_temp_files

    - name: Delete found old files in /tmp
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: absent
      loop: "{{ old_temp_files.files }}"

    - name: Clean up old directories in /tmp
      ansible.builtin.find:
        paths: "{{ temp_cleanup_path }}"
        file_type: directory
        age: "{{ temp_cleanup_days }}d"
        recurse: yes
      register: old_temp_dirs

    - name: Delete found old directories in /tmp
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: absent
      loop: "{{ old_temp_dirs.files }}"

    - name: Clear memory and cache (sync; echo 3 > /proc/sys/vm/drop_caches)
      ansible.builtin.command: /bin/bash -c "sync; echo 3 > /proc/sys/vm/drop_caches"
      changed_when: false

#    - name: Verify status of critical services (e.g., sshd, nginx, apache2, docker)
#      ansible.builtin.systemd:
#        name: "{{ item }}"
#        state: started
#        enabled: yes
#      loop:
#        - sshd
#        # - nginx
#        # - apache2
#        - docker



  handlers:
    - name: Reboot
      ansible.builtin.reboot:
        msg: "Reboot initiated by Ansible"
        connect_timeout: 5
        reboot_timeout: 600
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: whoami
      when:
        - allow_reboot | bool
