[ubuntu]
ubuntu2004 ansible_host=192.168.56.10
ubuntu2204 ansible_host=192.168.56.11
ubuntu2404 ansible_host=192.168.56.12

[debian]
debian11 ansible_host=192.168.56.20
debian12 ansible_host=192.168.56.21

[redhat]
centos7 ansible_host=192.168.56.30
rocky8 ansible_host=192.168.56.31
rocky9 ansible_host=192.168.56.32

[suse]
opensuse15 ansible_host=192.168.56.40

[bsd]
freebsd13 ansible_host=192.168.56.50
freebsd14 ansible_host=192.168.56.51

[linux:children]
ubuntu
debian
redhat
suse

[all:vars]
ansible_user=vagrant
ansible_ssh_private_key_file=~/.vagrant.d/insecure_private_key
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'

[testuser:children]
ubuntu
debian
redhat
suse
bsd

[testuser:vars]
ansible_user=testuser
ansible_password=testpass
