[ubuntu]
ubuntu2004 ansible_host=localhost ansible_port=2220
ubuntu2204 ansible_host=localhost ansible_port=2221
ubuntu2404 ansible_host=localhost ansible_port=2222

[debian]
debian11 ansible_host=localhost ansible_port=2223
debian12 ansible_host=localhost ansible_port=2224

[redhat]
rocky8 ansible_host=localhost ansible_port=2225
rocky9 ansible_host=localhost ansible_port=2226

[linux:children]
ubuntu
debian
redhat

[all:children]
linux

[all:vars]
ansible_user=root
ansible_ssh_private_key_file=docker/ssh/id_rsa
ansible_ssh_common_args=-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null
