- hosts: windows
  gather_facts: false
  tasks:
    - win_powershell:
        script: |
          $Ansible.Changed = $false
          $Ansible.Result = @{ size = (Get-Item C:\e2e\ssh\copied.txt).Length
            basic = (Get-Item WSMan:\localhost\Service\Auth\Basic).Value
            unencrypted = (Get-Item WSMan:\localhost\Service\AllowUnencrypted).Value }
      register: v
    - assert:
        that:
          - v.result.size == 200000
          - v.result.unencrypted == 'false'
          - v.result.basic == 'false'
