plays:
  - name: docker
    hosts: all
    become: true
    tasks:
      - name: Image
        docker_image:
          name: alpine
          tag: "3.20"
          state: present
        # Docker Hub fails now and then
        retries: 3
        delay: 10
      - name: Container
        docker_container:
          name: onigirazu-e2e
          image: alpine:3.20
          command: sleep 3600
          state: present
