name: "Simple test playbook"

plays:
  - name: "Create test files"
    hosts: "localhost"
    
    tasks:
      - name: "Create test directory"
        module: "file"
        args:
          path: "/tmp/onigirazu-test"
          state: "directory"
      
      - name: "Create test file"
        module: "file"
        args:
          path: "/tmp/onigirazu-test/hello.txt"
          state: "present"
