plays:
  - name: list variables as arguments
    hosts: all
    become: true
    vars:
      pkgs: [toilet, fortune-mod]
    tasks:
      - name: Packages from a list variable
        apt:
          name: "{{ pkgs }}"
          state: present
          update_cache: true
