- hosts: windows
  gather_facts: false
  tasks:
    - win_powershell:
        script: |
          $Ansible.Changed = $false
          $Ansible.Result = @{
            rdp = [bool](Get-LocalGroupMember -Group 'Remote Desktop Users' | Where-Object Name -like '*\e2e-member')
            backup = [bool](Get-LocalGroupMember -Group 'Backup Operators' | Where-Object Name -like '*\e2e-member') }
      register: v
    - assert:
        that: [v.result.rdp, not v.result.backup]
